### PR TITLE
Problem: Cannot build/use qt-mustache as library

### PR DESCRIPTION
**Pull request by sappo**
Solution: Make it possible to link statically or dynamically against
qt-mustache.

The mechanism used here is inspired by qt-solutions e.g.
https://github.com/qtproject/qt-solutions/tree/master/qtservice

### CODE REVIEW

**Comment by robertknight** [comment]
Given how tiny it is, I honestly don't see the point of building qt-mustache as a static or dynamically linked library and it adds too much complexity to the build config IMO. Is there another reason for doing this that I haven't considered?

**Comment by sappo** [comment]
From a maintainers perspective you're absolutely right. But from a users perspective with the current approach it is hard the integrate upstream changes. Because they have to be copied manually into the project. Whereas installing an new version of a library is easy. This especially comes in handy when using qt-mustache in multiple projects.

**Comment by robertknight** [comment]
> Because they have to be copied manually into the project.

The way I usually dealt with this was to check out vendor code as a Git subtree or Git submodule and then create a CMakeLists.txt or QMake build config as part of my own project which included the vendor code.

What would a minimal static library only config for QMake or CMakeLists.txt look like? If it is simple enough I'd reconsider.

**Comment by sappo** [comment]
The minimal static library only is the current qt-mustache.pri. I'm a huge fan of dynamic libs nicely layered on top of each other though ;).

**Pull request closed without merging**
